kind: pipeline
name: i18n CI
type: docker

steps:
  - name: gtts-deploy
    image: python:3.7
    # image: node:12.22.1-alpine
    commands:
      # - pip install requests
      # - pip install python-dotenv
      # - pip install translate
      # - pip install flask
      # install the dependency above in the deploy environment
      - pwd
      - tar -zcvf src.tar.gz src
      - python3 deploy.py


